# ─────────────────────────────────────────────
#  ansible/inventory/hosts.ini
#  Replace IP addresses with your actual IPs
# ─────────────────────────────────────────────

[devops_master]
devops-master ansible_host=172.31.38.134 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[devops_agent]
devops-agent  ansible_host=172.31.41.103  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[k8s_control_plane]
k8s-control-plane ansible_host=<K8S_MASTER_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[k8s_workers]
k8s-worker-1  ansible_host=<K8S_WORKER_IP>  ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[all:vars]
ansible_python_interpreter=/usr/bin/python3
